# Generated by Django 2.1 on 2021-07-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20210719_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='userProfile/test.png', upload_to='userProfile/'),
        ),
    ]
