# Generated by Django 2.1 on 2021-07-19 19:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_auto_20210719_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=cloudinary.models.CloudinaryField(default='userProfile/test.png', max_length=255, verbose_name='userProfile/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='project/'),
        ),
    ]
